#!/usr/bin/env bash
# Install the todo bar widget and the quick-intake hotkey on this Omarchy desktop.
#
#   desktop/install.sh [URL]        default URL: http://192.168.1.47:7670
#   desktop/install.sh --uninstall
#
# - copies omarchy-plugin/ to ~/.config/omarchy/plugins/dev.todo
# - writes ~/.config/todo/bar.json with the app URL (the widget reads it)
# - adds dev.todo to the bar's center section, right after dev.mediadeck
# - writes ~/.config/hypr/todo.lua (SUPER+ALT+T = quick add) and requires it from hyprland.lua;
#   rolls back if Hyprland reports config errors
# - installs todo-agent (runs customer hub tools here; asks for the API token once)
# - restarts omarchy-shell
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_DIR="$HOME/.config/omarchy/plugins/dev.todo"
SHELL_JSON="$HOME/.config/omarchy/shell.json"
HYPR_DIR="$HOME/.config/hypr"
HYPR_MAIN="$HYPR_DIR/hyprland.lua"
HYPR_TODO="$HYPR_DIR/todo.lua"
REQUIRE_LINE='pcall(require, "hypr.todo")  -- todo quick-add hotkey (managed by todo/desktop/install.sh)'

edit_bar() {  # $1 = add|remove
  python3 - "$SHELL_JSON" "$1" <<'PY'
import json, shutil, sys
path, action = sys.argv[1], sys.argv[2]
with open(path) as f:
    cfg = json.load(f)
layout = cfg.setdefault("bar", {}).setdefault("layout", {})
sections = [layout.setdefault(k, []) for k in ("left", "center", "right")]
present = any(w.get("id") == "dev.todo" for s in sections for w in s)
if action == "remove":
    if not present:
        sys.exit(0)
    for s in sections:
        s[:] = [w for w in s if w.get("id") != "dev.todo"]
else:
    if present:
        sys.exit(0)
    center = layout["center"]
    ids = [w.get("id") for w in center]
    at = ids.index("dev.mediadeck") + 1 if "dev.mediadeck" in ids else len(center)
    center.insert(at, {"id": "dev.todo"})
shutil.copy(path, path + ".bak-todo")
with open(path, "w") as f:
    json.dump(cfg, f, indent=2)
    f.write("\n")
print(f"bar: {action} dev.todo ({path}, backup .bak-todo)")
PY
}

if [[ "${1:-}" == "--uninstall" ]]; then
  edit_bar remove
  rm -rf "$PLUGIN_DIR"
  rm -f "$HYPR_TODO"
  [[ -x "$HOME/.local/bin/todo-agent" ]] && python3 "$HOME/.local/bin/todo-agent" uninstall || true
  sed -i '\|pcall(require, "hypr.todo")|d' "$HYPR_MAIN"
  hyprctl reload >/dev/null || true
  omarchy restart shell >/dev/null 2>&1 || true
  echo "Uninstalled (left ~/.config/todo/bar.json)."
  exit 0
fi

URL="${1:-http://192.168.1.47:7670}"

mkdir -p "$PLUGIN_DIR" "$HOME/.config/todo"
cp "$HERE/omarchy-plugin/manifest.json" "$HERE/omarchy-plugin/Widget.qml" "$PLUGIN_DIR/"
printf '{"url": "%s"}\n' "$URL" > "$HOME/.config/todo/bar.json"
echo "widget: $PLUGIN_DIR → $URL"

edit_bar add

cp "$HYPR_MAIN" "$HYPR_MAIN.bak-todo"
[[ -f "$HYPR_TODO" ]] && cp "$HYPR_TODO" "$HYPR_TODO.bak-todo"
cat > "$HYPR_TODO" <<'LUA'
-- Generated by todo/desktop/install.sh; edits here are overwritten.

o.bind("SUPER + ALT + T", "Todo: quick add", 'omarchy-shell dev.todo add ""')
LUA
grep -qF 'pcall(require, "hypr.todo")' "$HYPR_MAIN" || printf '\n%s\n' "$REQUIRE_LINE" >> "$HYPR_MAIN"
hyprctl reload >/dev/null
sleep 0.5
if [[ -n "$(hyprctl configerrors 2>/dev/null | grep -v '^$' || true)" ]]; then
  echo "Hyprland reported config errors; rolling back the hotkey:" >&2
  hyprctl configerrors >&2
  cp "$HYPR_MAIN.bak-todo" "$HYPR_MAIN"
  rm -f "$HYPR_TODO"
  hyprctl reload >/dev/null
  exit 1
fi
echo "hotkey: SUPER+ALT+T → quick add"

# Customer hub tools run through todo-agent (same agent as on the Mac). Its installer asks for
# the API token once; skip with TODO_SKIP_AGENT=1.
if [[ -z "${TODO_SKIP_AGENT:-}" ]]; then
  curl -fsSL "$URL/agent/install.sh" | sh -s -- "${TODO_AGENT_NAME:-Omarchy}" || echo "todo-agent install failed; retry: curl -fsSL $URL/agent/install.sh | sh" >&2
fi
# Earlier versions used a todo:// URL handler instead; remove it.
rm -f "$HOME/.local/bin/todo-launch" "$HOME/.local/share/applications/todo-launch.desktop" "$HOME/.config/todo/approved-launchers.json"

# Never `omarchy-shell shell rescanPlugins`: it has crashed the shell. Restart instead.
omarchy restart shell >/dev/null 2>&1 || echo "Restart the shell to load the widget: omarchy restart shell"
echo "Done."
